[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"

# https://stackoverflow.com/q/64129432/315168
overflow-checks = true

[workspace]
members = [
    "token",
    "pool"
]

